services:
  app:
    build: .
    container_name: fast_rag_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}
    extra_hosts:
      - "host.docker.internal:host-gateway"